# tasks file for wordpress, options
---
- name: add options
  command: "wp-cli --allow-root --no-color --path='{{ item.0.path }}' option {{ item.1.command }} '{{ item.1.name }}' '{{ item.1.value }}'"
  register: check_installation_options
  failed_when: false
  changed_when: "'Added' in check_installation_options.stdout"
  with_subelements:
    - wordpress_installs
    - options
  when: item.1.command == 'add'
  tags:
    - wordpress-options-add

- name: update options
  command: "wp-cli --allow-root --no-color --path='{{ item.0.path }}' option {{ item.1.command }} '{{ item.1.name }}' '{{ item.1.value }}'"
  register: check_installation_options
  changed_when: "'unchanged' not in check_installation_options.stdout"
  with_subelements:
    - wordpress_installs
    - options
  when: item.1.command == 'update'
  tags:
    - wordpress-options-update

- name: delete options
  command: "wp-cli --allow-root --no-color --path='{{ item.0.path }}' option {{ item.1.command }} '{{ item.1.name }}'"
  register: check_installation_options
  failed_when: false
  changed_when: "'Could not delete' not in check_installation_options.stderr"
  with_subelements:
    - wordpress_installs
    - options
  when: item.1.command == 'delete'
  tags:
    -   wordpress-options-delete
